"""empty message

Revision ID: 209d700e550e
Revises: 760af0b04b5d
Create Date: 2023-05-29 17:13:13.549568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209d700e550e'
down_revision = '760af0b04b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocklist',
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blocklist')
    # ### end Alembic commands ###
