"""empty message

Revision ID: 6048ce0ac17e
Revises: 209d700e550e
Create Date: 2023-05-29 18:35:53.434561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6048ce0ac17e'
down_revision = '209d700e550e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=80), nullable=True, default=''))
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=True, default=''))
        batch_op.add_column(sa.Column('lastname', sa.String(length=80), nullable=True, default=''))
    op.execute("UPDATE users SET surname = '';")
    op.execute("UPDATE users SET name = '';")
    op.execute("UPDATE users SET lastname = '';")
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('surname', existing_type=sa.String(length=80), existing_nullable=True,
                              existing_default='', nullable=False)
        batch_op.alter_column('name', existing_type=sa.String(length=80), existing_nullable=True,
                              existing_default='', nullable=False)
        batch_op.alter_column('lastname', existing_type=sa.String(length=80), existing_nullable=True,
                              existing_default='', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lastname')
        batch_op.drop_column('name')
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
