"""empty message

Revision ID: 760af0b04b5d
Revises: 6e41481fe6d5
Create Date: 2023-05-29 17:00:57.165155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760af0b04b5d'
down_revision = '6e41481fe6d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=87),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=87),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
