version: '3'

services:
  auth_service_back:
    image: auth_service:1.2.2
    depends_on:
      - auth_db
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - /e/nikakv/_DIPLOMA/backend/auth_service:/app
    env_file:
      - auth_service/.env
    restart: always
  auth_db:
    image: postgres:latest
    volumes:
      - auth_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    restart: always
  gateway_service_back:
    image: gateway_service:1.3
    depends_on:
      auth_service_back:
        condition: service_started
      gateway_redis:
        condition: service_started
      shop_info_service_back:
        condition: service_started
      item_service_back:
        condition: service_started
      report_service_back:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - 5001:5001
    links:
      - rabbitmq
    working_dir: /app
    volumes:
      - /e/nikakv/_DIPLOMA/backend/gateway_service:/app
    env_file:
      - ./gateway_service/.env
    restart: always
  gateway_redis:
    image: redislabs/redismod
    restart: always
    ports:
      - 6379:6379
    volumes:
      - gateway_db:/data
      - ./gateway_service/db/redis.conf:/usr/local/etc/redis/redis.conf
    #  TODO: Make redis to read config files; NOW REDIS IS UNPROTECTED
  shop_info_service_back:
    image: shop_info_service:1.0.1
    depends_on:
      - shop_info_db
    ports:
      - 5002:5002
    working_dir: /app
    volumes:
      - /e/nikakv/_DIPLOMA/backend/shop_info_service:/app
    env_file:
      - ./shop_info_service/.env
    restart: always
  shop_info_db:
    image: postgres:latest
    volumes:
      - shop_info_db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: shop_info
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    restart: always
  item_service_back:
    image: item_service:1.0
    depends_on:
      - item_db
    ports:
      - 5003:5003
    working_dir: /app
    volumes:
      - /e/nikakv/_DIPLOMA/backend/item_service:/app
    env_file:
      - ./item_service/.env
    restart: always
  item_db:
    image: postgres:latest
    volumes:
      - item_db:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: item
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    restart: always
  report_service_back:
    image: report_service:1.1
    depends_on:
      - report_db
    ports:
      - 5004:5004
    working_dir: /app
    volumes:
      - /e/nikakv/_DIPLOMA/backend/report_service:/app
    env_file:
      - ./report_service/.env
    restart: always
  report_db:
    image: bitnami/mongodb
    environment:
      MONGODB_DATABASE: reports
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: 1234
      MONGODB_ROOT_PASSWORD: 1234
    volumes:
      - report_db:/data/db
      - report_db_config:/data/configdb
    ports:
      - 27017:27017
    restart: always
  email_service_back:
    image: email_service:1.1
    depends_on:
      email_redis:
        condition: service_started
      gateway_service_back:
        condition: service_started
    ports:
      - 5005:5005
    working_dir: /app
    volumes:
      - /e/nikakv/_DIPLOMA/backend/email_service:/app
    env_file:
      - ./email_service/.env
    restart: always
  email_redis:
    image: redislabs/redismod
    restart: always
    ports:
      - 6380:6379
    volumes:
      - email_db:/data
      - ./gateway_service/db/redis.conf:/usr/local/etc/redis/redis.conf
    #  TODO: Make redis to read config files; NOW REDIS IS UNPROTECTED
  rabbitmq:
    image: rabbitmq-curl:1.0
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always
    volumes:
      - rabbit:/var/lib/rabbitmq/mnesia/
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq/definitions.json:/opt/definitions1.json
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  auth_db:
  gateway_db:
  shop_info_db:
  item_db:
  report_db:
  report_db_config:
  email_db:
  rabbit:
