"""empty message

Revision ID: 1aebaa3a29a5
Revises: 
Create Date: 2023-05-31 16:34:45.907815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aebaa3a29a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_name', sa.String(length=80), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'folder_name')
    )
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_folders_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index('shop_foldername_index', ['shop_id', 'folder_name'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=512), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('COMMODITY', 'SERVICE', name='itemtypeenum'), nullable=False),
    sa.Column('price', sa.Numeric(scale=2), nullable=False),
    sa.Column('unit', sa.Enum('PIECE', 'KILOGRAM', 'LITER', name='unitsenum'), nullable=True),
    sa.Column('count_existing', sa.Double(), nullable=True),
    sa.Column('article', sa.Numeric(precision=5, scale=0), nullable=False),
    sa.Column('bar_code', sa.Numeric(precision=13, scale=0), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'article'),
    sa.UniqueConstraint('shop_id', 'bar_code'),
    sa.UniqueConstraint('shop_id', 'item_name')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_article'), ['article'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_bar_code'), ['bar_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_item_name'), ['item_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index('shop_ar_code_index', ['shop_id', 'bar_code'], unique=False)
        batch_op.create_index('shop_article_index', ['shop_id', 'article'], unique=False)
        batch_op.create_index('shop_folder_index', ['shop_id', 'folder_id'], unique=False)
        batch_op.create_index('shop_name_index', ['shop_id', 'item_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('shop_name_index')
        batch_op.drop_index('shop_folder_index')
        batch_op.drop_index('shop_article_index')
        batch_op.drop_index('shop_ar_code_index')
        batch_op.drop_index(batch_op.f('ix_items_shop_id'))
        batch_op.drop_index(batch_op.f('ix_items_item_name'))
        batch_op.drop_index(batch_op.f('ix_items_folder_id'))
        batch_op.drop_index(batch_op.f('ix_items_bar_code'))
        batch_op.drop_index(batch_op.f('ix_items_article'))

    op.drop_table('items')
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_index('shop_foldername_index')
        batch_op.drop_index(batch_op.f('ix_folders_shop_id'))

    op.drop_table('folders')
    # ### end Alembic commands ###
